apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: catalog-service

  template:
    metadata:
      labels:
        app: catalog-service

    spec:
      containers:
      - name: catalog-service

        image: smartretailshr.azurecr.io/catalog-service:exam

        ports:
        - containerPort: 3000

        env:
        - name: APP_VERSION
          value: "1.0"
